### ISSUE TITLE
Request: 履歴の参照をしたときにエラーになる。

### ISSUE THREAD

**Issue by InoueKenichi** [c-hagi/sample#9]
事象
実行経過を記載している一覧のボタンを押したときにエラーが発生している。

期待
ボタンを押したときにエラーが解消されていること

参考
画像を参照
履歴のボタン
![issue](https://user-images.githubusercontent.com/58497349/101592248-49267e00-3a31-11eb-86f1-b6220c41ec24.png)

ボタンを押したときのエラー
![error](https://user-images.githubusercontent.com/58497349/101592246-47f55100-3a31-11eb-858b-dbac772fbcf0.png)

**Comment by InoueKenichi** [comment]
どうやら関数が未定義のよう？
https://github.com/c-hagi/sample/pull/10#pullrequestreview-548043579

**Comment by InoueKenichi** [comment]
うまく動いていますね。

**Comment by InoueKenichi** [comment]
解決したので閉じます。

**Comment by c-hagi** [comment]
ありがとうございます。
